### ISSUE TITLE
HbbTV Reference App - including 3rd party material

### ISSUE THREAD

**Issue by bobcampbell-resillion** [osmart-community/.github#4]
Forgot to highlight this in my presentation but may be useful for this community to know HbbTV is happy to reference relevant 3rd party streams via its reference application.

See these [guidelines](https://github.com/HbbTV-Association/ReferenceApplication/blob/master/doc/3rdpartycontent.md) at our [github project](https://github.com/HbbTV-Association/ReferenceApplication)

**Comment by jordijoangimenez** [comment]
Added to the readme.md. Thanks, @bobcampbell-resillion
